### ISSUE TITLE
Game Gear games that are not working on the lastest Bizhawk Dev 2020-11-07

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#1157]
LAST MODIFIED (July 22 2019)

A quick summary of the games that are not fixed yet
- [x] Pro Yakyuu GG League (doesn't boot)
- [x] World Derby (Intense glitching when you want to start the actual game from the menu) 
- [x] Power Drive (intense flickers)
- [x] Tarzan : Lord of the Jungle ( glitched number at the bottom of the screen)
- [x] Fray: Shugyouhen (minor graphic glitches on the right side of the playfield)
- [x] Urban Strike (hissing and irritating static that is not present in Kega during the intro where the music play)
- [x] Pop Breaker (Input doesn't work)
NOTE : According to SMS Power (http://www.smspower.org/Development/PopBreaker-GG). Pop Breaker has an issue if played on a non Japanese Game Gear. Changing the region to Japan does not fix the problem.
"Pop Breaker does not work on export Game Gear systems because the code to read the start button does not mask out the region bit (port 00h bit 6)."

On Kega Fusion:
- Fray: Shugyouhen doesn't display graphics glitches on the right side of the playfield.

Picture 1 KEGA FUSION
![kega](https://user-images.githubusercontent.com/24578279/46613525-738ef080-cae1-11e8-9e53-aa34b72ebdd9.PNG)

Picture 2 BIZHAWK LASTEST VERSION
![bizhawk](https://user-images.githubusercontent.com/24578279/46613526-738ef080-cae1-11e8-80d6-37c1ecd02304.PNG)

**Comment by alyosha-tas** [comment]
Thanks for the testing. This will probably take a while to sort out.

Pac Attack though is fixed by basic emulation (tracking writes) to Port $05 (link cable)

I don't understand the graphics corruption in some of the others, it looks like some are combination SMS / GG ROMs? maybe something isn't being initialized correctly.

**Comment by Glitcholog** [comment]
EDIT : I added Castle of Illusion Starring Mickey Mouse (USA, Europe) to the list of the game who ask for bios

**Comment by alyosha-tas** [comment]
Terminotr needed SRAM to display background, probably for smoe others too.

**Comment by alyosha-tas** [comment]
I added in COmpatibility mode for the core and added some of the games to the DB.

Here is te current list of not working games (or ones that I haven't looked at yet):

Prince of Persia (USA, Europe)
Predator 2 (USA, Europe)
WWF Wrestlemania Steel Cage Challenge (Europe)
Castle of Illusion Starring Mickey Mouse (USA, Europe)
Rastan Saga (Japan)
Double Dragon (USA, Europe) (missing background)
World Derby (Japan) Some menu and the main game are horribly glitched, thought the game does not crash)
Ecco The Dolphin (USA) (pink screen, unplayable)

**Comment by Glitcholog** [comment]
Thank you for the quick answer! So far, I have recorded about 200 game gear out of 363 for my youtube project, so im glad more game are going to be fix!

**Comment by Glitcholog** [comment]
Just a quick headup since the issues was referenced. The test were done on the dev version

The Terminator is fixed in the dev, its background now appears
Outrun Europe and R.C. Grand Prix, which are rare case of Game Gear games using the SMS compatibility mode, now work as well
Pac-Attack is fixed

Now, for the games that does not work or are super glitched

Black/Pink screen or unplayable
Pro Yakyuu GG League
Pro Yakyuu GG League '94
Ecco the Dolphin

Games asking for the firmware, not being regonised by Bizhawk
Prince of Persia (USA, Europe)
Predator 2 (USA, Europe)
WWF Wrestlemania Steel Cage Challenge (Europe)
Castle of Illusion Starring Mickey Mouse (USA, Europe)
Rastan Saga (Japan)

The following games can be run but have heavy glitches
Double Dragon (USA, Europe) (missing background)
Taito Chase H.Q. (USA) (Horribly glitched to the point that its unplayable)
World Derby (Japan) Some menu and the main game are horribly glitched, thought the game does not crash)

**Comment by Glitcholog** [comment]
here another one 

Tails Skypatrol
![skyepatrol](https://user-images.githubusercontent.com/24578279/45581749-b0b0eb80-b871-11e8-8897-dc496c3c7ca6.PNG)

**Comment by Asnivor** [comment]
Double dragon is now fixed in the master branch (latest dev build)

**Comment by Asnivor** [comment]
Ok, so I have moved:

```
Prince of Persia (USA, Europe)
Predator 2 (USA, Europe)
WWF Wrestlemania Steel Cage Challenge (Europe)
Castle of Illusion Starring Mickey Mouse (USA, Europe)
Rastan Saga (Japan)
```

from gamedb_sega_sms.txt to gamedb_sega_gg.txt and set the **GG_in_SMS** flag. This gets those games running (whereas just setting the compat flag within gamedb_sega_sms.txt does _not_).

@alyosha-tas if this is incorrect for any reason let me know and we can change back.

Terminator **was** working before (maybe an earlier fix), but controls were not working. This is resolved after the move.

**Comment by alyosha-tas** [comment]
Thanks for sorting out some of these . I know it’s a tedious process.

**Comment by Asnivor** [comment]
So Tails Skypatrol is the same issue as #1323 and should be resolved when that is

**Comment by Asnivor** [comment]
Tails skypatrol is now working

**Comment by Glitcholog** [comment]
small update, Taito Chase HQ seems to work very well in the 21 septembre build, it may have been related to Tails skypatrol and many other game with glitched graphics

**Comment by Glitcholog** [comment]
how can I add that SRAM?

**Comment by Asnivor** [comment]
Ecco is now fixed via https://github.com/TASVideos/BizHawk/commit/b747ac22d79a49d165fcaae7e611a3d3695a34a8

**Comment by Asnivor** [comment]
@Glitcholog Riddick Bow boxing life bars flicker exactly the same on Kega Fusion, so I'm assuming this is how it is supposed to be.

**Comment by Glitcholog** [comment]
added Evander Holyfield's 'Real Deal' Boxing (USA, Europe) in the list of non working game

**Comment by alyosha-tas** [comment]
are you checking in the dev build @Glitcholog ? 

The same fix that worked on Ecco was also supposed to fix Real Deal Boxing (at least on Ekeeke's commit.)

**Comment by Glitcholog** [comment]
I checked on the september 21 build, I forgot to download the lastest version of it

So yeah, Evender is fixed, and it seems that it fixed Pro Yakyuu GG League '94 as well as the game boot and works now, but not the original Pro Yakyuu GG League

**Comment by Glitcholog** [comment]
Added Juan Pung II and Super Tetris (even if they are pirate game, they might work by adding them to the DB since they are SMSGG games).

According to this list , there is also Cave Dude and Street Hero, 2 unrealized SMSGG game

http://www.smspower.org/Tags/SMS-GG?sid=2ab30a4c876941cc71af5515595aae01

**Comment by Asnivor** [comment]
@Glitcholog : I have moved the above games to gamedb_sega_gg where necessary and set SMS compatibility mode. Two points:

1. All these games appeared to be working for me anyway, although they were being loaded as SMS rather than GG with SMS compatibility, but maybe there is something that happens in your workflow that means this is a problem (movies maybe?).
2. The two pirate games were already present in gamedb_sega_sms.txt

Please test with the latest dev version and strike them through on here when you are happy.

**Comment by Glitcholog** [comment]
Added Urban Strike to the list, the game sounds is weird at the intro sequence, which doesn't happen in Kega

**Comment by Glitcholog** [comment]
added Pop Breaker to the list, being unable to actually play the game because of the input

**Comment by Glitcholog** [comment]
UPDATE (MAY 26 2019)
I did a tour with the remaining non working or glitched games with the May 13 dev version of Bizhawk
Pro Yakyuu GG League (Still doesn't boot)
World Derby (Intense glitching is present, but the game is playable now)
Power Drive (After close investigation, the flickering and graphical glitches are present on a stock Game Gear as well, so it is considered working now)
Fray: Shugyouhen (still have its minor glitches on the right of the playfield)
Urban Strike (The weird statics buzz plays during the intro)
Pop Breaker (Input doesn't work)
According to SMS Power (http://www.smspower.org/Development/PopBreaker-GG). Pop Breaker has an issue if played on a non Japanese Game Gear. Changing the region to Japan does not fix the proble.
"Pop Breaker does not work on export Game Gear systems because the code to read the start button does not mask out the region bit (port 00h bit 6)."

**Comment by alyosha-tas** [comment]
Cool thanks for your continued research on this. Pop Breaker at least seems fixable.

**Comment by alyosha-tas** [comment]
World Derby is fixed, just needed SRAM.

**Comment by Glitcholog** [comment]
Thanks for the update, ill make a test for this game as soon as I am able with the lastest dev

**Comment by Glitcholog** [comment]
In the lasted Dev build, World Derby's intense glitching has ended. Its now working correctly

The four others game still have their bug, Pro Yakyuu GG League being the last commercial Game Gear game that does not boot.

**Comment by alyosha-tas** [comment]
Pro Yakyuu is fixed, it needed the EEPROM mapper.

I'm also checking off Fray, the same glitch on the right is clearly visible in the screenshot in kega.

**Comment by Glitcholog** [comment]
Just a quick head up for the Game Gear's game.

For now, Pop Breaker is the only non-playable game remaining in the entire Game Gear library. Fray in Magical Adventure and Urban Strike still display their respective problem, but are playable. These bugs are not present in KEGA. In Urban Strike, video editing can bypass the sound problem. I am aware that GG Aleste 3 is coming out in December 2020, but I don't expect it to be emulated for a while.

**Comment by alyosha-tas** [comment]
I checked in 2.6.3 and no longer hear any audio issues in Urban Strike (compared to ex 2.3.2), so it must have been fixed somewhere along the way, I'll mark that one off.

**Comment by alyosha-tas** [comment]
Fray: Shugyouhen moved to #2998 
Closing.
