### ISSUE TITLE
[PCE] OutRun (J) Problems with BizHawk 2.3

### ISSUE THREAD

**Issue by danylopez123** [TASEmulators/BizHawk#1266]
I tried making a TAS from OutRun for the PC Engine, after finishing it, while capturing the frames, it always crashes the emulator when it changes the resolution when it gets to the map screen.

I also tried it from "Config and Record AVI/WAV" but still the same problem.

It ALSO happens sometimes (Or mostly) when not even capturing the frames.

**Comment by Asnivor** [comment]
@danylopez123 There is a chance that this is now fixed in the latest dev build. Could you please test and let us know?

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by danylopez123** [comment]
The same problem still happens.
This time when i was dumping the frames, i get these 2 errors:
(Sorry, my PC is Spanish)

---------------------------
AVIFIL32 Thread died:

System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.

   en BizHawk.Client.EmuHawk.AviWriter.AviWriterSegment.AddFrame(IVideoProvider source)

   en BizHawk.Client.EmuHawk.AviWriter.threadproc()
---------------------------
Aceptar   
---------------------------

---------------------------

---------------------------
Video dumping died:

System.Exception: AVI Worker thread died!

   en BizHawk.Client.EmuHawk.AviWriter.AddSamples(Int16[] samples)

   en BizHawk.Client.EmuHawk.MainForm.AvFrameAdvance()
---------------------------
Aceptar   
---------------------------

**Comment by danylopez123** [comment]
@Asnivor 
Sorry, but the ame problem is still happening
It still crashes when it gets to the map screen but when capturing the frames, this happened when it got to the map screen:
(Sorry, some text is in Spanish due i live in Spain)

![imagen](https://user-images.githubusercontent.com/17708894/46103105-4a608d00-c1d0-11e8-8bbf-3192a3a97f5f.png)

And
![imagen](https://user-images.githubusercontent.com/17708894/46103116-51879b00-c1d0-11e8-93d4-b054298452b2.png)

**Comment by Asnivor** [comment]
Ok thanks for the update. It was a long shot anyway, but worth checking.

**Comment by EZGames69** [comment]
Does it only crash when you are dumping frames or does it sometimes crash when playing normally?

**Comment by alyosha-tas** [comment]
Tested in latest build and the game still crashes the emulator even during casual play.
