### ISSUE TITLE
Undo is broken in Watch editor's addr `TextBox`

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3758]
Title. Can be reproduced by double-clicking a watch, then pressing 0, Ctrl+Z, Ctrl+Z.

Still present as of 26b39fb56 (last before SDL2 added as rundep). May not affect Windows. Not fixed by #3684.

**Comment by Asnivor** [comment]
This is working fine here on Windows -> master branch, on both debug and release builds.
Is this a linux only thing or is it maybe fixed now?

**Comment by YoshiRulz** [comment]
Still broken at 4c69ce4e27224c6ddf6766b98a25acf38d6e1bb2. Must be Mono.
