### ISSUE TITLE
Mayflash N64 Controller Adapter - Analog, C-buttons and d-pad not working/not responsive

### ISSUE THREAD

**Issue by MGZero** [TASEmulators/BizHawk#4280]
### Summary
Using a Mayflash USB N64 controller adapter:
Analog stick, d-pad and c-buttons are not responsive while binding controller inputs. Other buttons work fine. Tried with several N64 controllers, as well as other emulators to rule out the adapter. Only able to reproduce in Bizhawk, regardless of N64 controller used.

### Repro
1. Plug in a first party N64 controller via USB adapter
2. Attempt to set bindings for D-pad, C-buttons or analog stick.
Expected behavior: Input is detected from the controller and bindings are set
Actual behavior: No input detected, it's as if nothing is being pressed

### Host system
Bizhawk 2.10 WIndows 10 Pro 22H2 AMD Ryzen 5600x
      Mayflash adapter in question: https://www.amazon.com/dp/B002B9FIUU

**Comment by Morilli** [comment]
Could you check whether you get the same results in the [latest dev build](https://github.com/TASEmulators/BizHawk?tab=readme-ov-file#development-builds) as well? This may have been fixed already.

**Comment by MGZero** [comment]
@Morilli Behaving a bit differently on the latest. C-button and D-pad still don't work, and the analog stick still does not work on the analog controls tab. However, the analog on the normal controls tab is registering as the D-pad

**Comment by CasualPokePlayer** [comment]
Does it use `J1` or `X1` here?

**Comment by CasualPokePlayer** [comment]
Seems this is (or rather, was?) a known issue in SDL: https://github.com/libsdl-org/SDL/issues/6079

The problem with it is that its VID/PID collided with another controller, so you'd end up getting nonsensical results from an SDL_GameController. Seems it needs to have mappings created using a program linked in that issue, which the OP apparently never did.

**Comment by CasualPokePlayer** [comment]
[controllermap.zip](https://github.com/user-attachments/files/19544362/controllermap.zip)
This would be the controller mapping program (built off latest SDL2 commit), could you try running this with that N64 adapter?

**Comment by MGZero** [comment]
@CasualPokePlayer That does detect the controller correctly, though the N64 controller doesn't have enough buttons to map it all to the xbox controller on screen haha. It does recognize all the inputs though!

**Comment by CasualPokePlayer** [comment]
What was the output given?

**Comment by YoshiRulz** [comment]
@MGZero 

edit: closing as stale

**Comment by ExtremelyLazyCat** [comment]
Opened a PR in SDL to add support for the Mayflash, if you want you can also try my SDL2 DLL I made:

[SDL2.zip](https://github.com/user-attachments/files/29728140/SDL2.zip)
